name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fecth-depth: 0
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DCOKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DCOKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
